"""Levels: which toast appears, how much health it has and how many Duckcoins it gives.

Levels are generated by formulas, so they never run out. To rebalance the game,
change the numbers in the "Balancing" section below and run the balance
simulator to see how long the game takes:

    python -m tools.simulate_balance
"""
from . import config

# Toast images in the order they appear (file names in assets/images/toasts).
# Every toast gets 5 levels: it starts as the boss and then shows up 4 more times.
# After the last toast, the list starts over (with stronger toasts).
TOASTS = [
    'nerd_toast',
    'happy_toast',
    'upside_down_toast',
    'moldy_toast',
    'coquette_toast',
    'question_mark_toast',
    'clown_toast',
    'uwu_toast',
    'tiny_toast',
    'hat_toast',
    'what_are_you_doing_toast',
]

# --- Balancing ---
STARTING_HEALTH = 50      # health of the toast on level 1
HEALTH_GROWTH = 1.22      # each level has this many times more health than the previous one
STARTING_REWARD = 30      # Duckcoins for beating level 1
REWARD_GROWTH = 1.4       # each level gives this many times more Duckcoins than the previous one
BOSS_HEALTH_MULTIPLIER = 3   # bosses have this many times the health of a normal toast
BOSS_REWARD_MULTIPLIER = 3   # ...and give this many times the Duckcoins


def is_boss(level):
    return level % config.BOSS_EVERY_N_LEVELS == 0


def toast_for(level):
    index = level // config.BOSS_EVERY_N_LEVELS
    return TOASTS[index % len(TOASTS)]


def health_for(level):
    health = STARTING_HEALTH * HEALTH_GROWTH ** (level - 1)
    if is_boss(level):
        health *= BOSS_HEALTH_MULTIPLIER
    return round(health)


def reward_for(level):
    reward = STARTING_REWARD * REWARD_GROWTH ** (level - 1)
    if is_boss(level):
        reward *= BOSS_REWARD_MULTIPLIER
    return round(reward)


def get_level(level):
    """Return (toast_image, health, reward) for a level."""
    return toast_for(level), health_for(level), reward_for(level)
