[project]
name = "duck-vs-toast"
version = "0.1.0"
description = "A clicker game where ducks battle against evil toasts."
requires-python = ">=3.10"
dependencies = ["pygame>=2.6"]

[tool.ruff]
line-length = 110

[tool.ruff.lint]
# https://docs.astral.sh/ruff/configuration/
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']
